---

- name: Download Jenkins repo yum URL for
  get_url:
    url: "{{jenkins.repo_URL}}"
    dest: /etc/yum.repos.d/jenkins.repo
  become: true
- name: Import GPG Key
  rpm_key:
    state: present
    key: "{{jenkins.gpg_key}}"

- name: Install Jenkins in ec2 instance
  apt:
    name: jenkins
    state: present

- name: Change Jenkins JAVA options
  lineinfile:
    dest=/etc/sysconfig/jenkins
    regexp=^JENKINS_JAVA_OPTIONS=
    line=JENKINS_JAVA_OPTIONS="{{jenkins.JAVA_OPTIONS}}"
  become: true

- name: Start Jenkins service and enable on boot
  service:
    name: jenkins
    state: started
    enabled: yes
