---
- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'


- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: no
    
- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - openjdk-8-jre-headless
    - ca-certificates
