---

- name: Install Java 8 in EC2 instance.
  yum:
    name: "{{java.VERSION}}"
    state: present
  become: true

- name: Correct the alternatives to change default Java version.
  alternatives:
    name: java
    link: /bin/java
    path: "{{java.ALTERNATIVES}}"
