
- name: Create an ec2 instance
  hosts: localhost
  gather_facts: true
  vars:
    keypair: linuxec2
    instance_type: t2.micro
    security_group: my_securitygroup
    image:  ami-0f4aeaec5b3ce9152
    region: us-east-2
  tasks:
   - name: Launch an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ t2.micro }}"
         image: "{{  ami-0f4aeaec5b3ce9152 }}"
         wait: true
         region: "{{ us-east-2 }}"
         vpc_subnet_id: subnet-4ecc0525
         assign_public_ip: yes
      register: ec2
