---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name:launch an ec2 instance
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: ansibleubuntu
        instance_type: t2.micro
        image:  ami-0f4aeaec5b3ce9152
        wait: yes
        count: 1
        region: us-east-2
